In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import matplotlib.pyplot as plt
import numpy as np
import math

In [10]:
B,T,C=4,8,2
torch.manual_seed(1337)
xbow=torch.zeros((B,T,C),dtype=float)
x=torch.randint(24,(B,T,C),dtype=float)
#Token can't communicate with future token

for b in range(B):
    for t in range(T):
        xprev=x[b,:t+1]
        print(xprev)
        xbow[b,t]=torch.mean(xprev)


tensor([[ 7., 13.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.],
        [18.,  2.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.],
        [18.,  2.],
        [20.,  0.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.],
        [18.,  2.],
        [20.,  0.],
        [ 9., 22.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.],
        [18.,  2.],
        [20.,  0.],
        [ 9., 22.],
        [ 6., 10.]], dtype=torch.float64)
tensor([[23., 16.]], dtype=torch.float64)
tensor([[23., 16.],
        [ 9., 19.]], dtype=torch.float64)


In [11]:
t=torch.tril(torch.ones(T,T))
wei=torch.zeros((T,T))
wei=wei.masked_fill(t==0,float('-inf'))
wei=F.softmax(wei,dim=1)

In [12]:
x

tensor([[[ 7., 13.],
         [20., 16.],
         [23.,  1.],
         [23.,  2.],
         [18.,  2.],
         [20.,  0.],
         [ 9., 22.],
         [ 6., 10.]],

        [[23., 16.],
         [ 9., 19.],
         [ 5.,  6.],
         [14., 18.],
         [18.,  9.],
         [ 0.,  3.],
         [17., 20.],
         [23.,  3.]],

        [[ 6., 17.],
         [15., 11.],
         [19.,  1.],
         [ 3., 20.],
         [16.,  0.],
         [21., 15.],
         [18., 11.],
         [ 9., 12.]],

        [[23., 17.],
         [20., 14.],
         [20., 12.],
         [10., 21.],
         [22., 15.],
         [12., 10.],
         [18., 19.],
         [17., 10.]]], dtype=torch.float64)

In [15]:
pe=torch.zeros(65,512)
position=torch.arange(65,dtype=torch.float).unsqueeze(1)
div_term=torch.exp(-torch.arange(0,512,2)*math.log(10000)/512)

In [42]:
a=position*div_term

In [44]:
pe[:,0::2]=torch.sin(position*div_term)
pe

In [46]:
torch.sin(position*div_term)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  8.2186e-01,  8.0196e-01,  ...,  1.1140e-04,
          1.0746e-04,  1.0366e-04],
        [ 9.0930e-01,  9.3641e-01,  9.5814e-01,  ...,  2.2279e-04,
          2.1492e-04,  2.0733e-04],
        ...,
        [-7.3918e-01, -1.1848e-01,  9.1145e-01,  ...,  6.9066e-03,
          6.6625e-03,  6.4271e-03],
        [ 1.6736e-01, -8.8357e-01,  8.7441e-01,  ...,  7.0180e-03,
          6.7700e-03,  6.5307e-03],
        [ 9.2003e-01, -8.8825e-01,  1.3325e-01,  ...,  7.1294e-03,
          6.8774e-03,  6.6344e-03]])

In [45]:
pe.shape

torch.Size([65, 512])