In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F 
import matplotlib.pyplot as plt
import numpy as np

In [19]:
torch.manual_seed(1337)

In [26]:
B,T,C=4,8,2
torch.manual_seed(1337)
xbow=torch.zeros((B,T,C),dtype=float)
x=torch.randint(24,(B,T,C),dtype=float)
#Token can't communicate with future token

for b in range(B):
    for t in range(T):
        xprev=x[b,:t+1]
        print(xprev)
        xbow[b,t]=torch.mean(xprev)


tensor([[ 7., 13.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.],
        [18.,  2.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.],
        [18.,  2.],
        [20.,  0.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.],
        [18.,  2.],
        [20.,  0.],
        [ 9., 22.]], dtype=torch.float64)
tensor([[ 7., 13.],
        [20., 16.],
        [23.,  1.],
        [23.,  2.],
        [18.,  2.],
        [20.,  0.],
        [ 9., 22.],
        [ 6., 10.]], dtype=torch.float64)
tensor([[23., 16.]], dtype=torch.float64)
tensor([[23., 16.],
        [ 9., 19.]], dtype=torch.float64)


In [30]:
t=torch.tril(torch.ones(T,T))
wei=torch.zeros((T,T))
wei=wei.masked_fill(t==0,float('-inf'))
wei=F.softmax(wei,dim=1)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [11]:
x

tensor([[[17.,  3.],
         [14., 19.],
         [ 4.,  6.],
         [12.,  0.],
         [15.,  0.],
         [ 9.,  1.],
         [15.,  0.],
         [22., 13.]],

        [[20., 11.],
         [19., 16.],
         [ 5.,  4.],
         [ 0., 18.],
         [ 9.,  1.],
         [16.,  4.],
         [11.,  2.],
         [18., 15.]],

        [[ 8., 22.],
         [19., 17.],
         [ 8.,  9.],
         [ 2., 17.],
         [15., 16.],
         [19., 18.],
         [18.,  4.],
         [17., 13.]],

        [[ 2.,  7.],
         [ 3.,  7.],
         [23., 22.],
         [ 2.,  9.],
         [18.,  4.],
         [10., 19.],
         [16., 10.],
         [ 6., 13.]]], dtype=torch.float64)